module.exports = {
    important: false,
    purge: {
      enabled: true,
      content: ['./src/**/*.html',
      './src/**/*.tsx',
      './src/**/*.jsx']
    },
    corePlugins: {
      divideColor: false,
      divideOpacity: false,
      divideWidth: false,
      float: false,
      whitespace: false,
      scale: false,
      skew: false,
      placeholderOpacity: false,
      borderOpacity: false,
      boxShadow: false,
    },
    variants: {
      accessibility: [],
      alignContent: ['responsive'],
      alignItems: ['responsive'],
      alignSelf: ['responsive'],
      appearance: [],
      backgroundAttachment: [],
      backgroundColor: ['responsive', 'hover'],
      backgroundOpacity: ['responsive', 'hover'],
      backgroundPosition: ['responsive'],
      backgroundRepeat: ['responsive'],
      backgroundSize: ['responsive'],
      borderCollapse: ['responsive'],
      borderColor: [],
      borderOpacity: [],
      borderRadius: ['responsive'],
      borderStyle: ['responsive'],
      borderWidth: ['responsive'],
      boxShadow: [],
      boxSizing: ['responsive'],
      clear: ['responsive'],
      cursor: ['responsive'],
      display: ['responsive'],
      divideColor: [],
      divideOpacity: [],
      divideWidth: [],
      fill: ['responsive'],
      flex: ['responsive'],
      flexDirection: ['responsive'],
      flexGrow: ['responsive'],
      flexShrink: ['responsive'],
      flexWrap: ['responsive'],
      float: ['responsive'],
      fontFamily: ['responsive'],
      fontSize: ['responsive'],
      fontSmoothing: ['responsive'],
      fontStyle: ['responsive'],
      fontWeight: ['responsive', 'hover'],
      height: ['responsive'],
      inset: [],
      justifyContent: ['responsive'],
      letterSpacing: ['responsive'],
      lineHeight: ['responsive'],
      listStylePosition: ['responsive'],
      listStyleType: ['responsive'],
      margin: ['responsive'],
      maxHeight: ['responsive'],
      maxWidth: ['responsive'],
      minHeight: ['responsive'],
      minWidth: ['responsive'],
      objectFit: ['responsive'],
      objectPosition: [],
      opacity: [],
      order: ['responsive'],
      outline: ['responsive'],
      overflow: ['responsive'],
      padding: ['responsive'],
      placeholderColor: [],
      placeholderOpacity: [],
      pointerEvents: ['responsive'],
      position: ['responsive'],
      resize: ['responsive'],
      rotate: ['responsive'],
      scale: ['responsive'],
      skew: ['responsive'],
      space: ['responsive'],
      stroke: ['responsive'],
      strokeWidth: ['responsive'],
      tableLayout: ['responsive'],
      textAlign: ['responsive'],
      textColor: ['hover'],
      textDecoration: [],
      textOpacity: ['responsive', 'hover'],
      textTransform: ['responsive'],
      transform: ['responsive'],
      transformOrigin: ['responsive'],
      transitionDelay: ['responsive'],
      transitionDuration: ['responsive'],
      transitionProperty: ['responsive'],
      transitionTimingFunction: ['responsive'],
      translate: [],
      userSelect: ['responsive'],
      verticalAlign: ['responsive'],
      visibility: ['responsive'],
      whitespace: ['responsive'],
      width: ['responsive'],
      wordBreak: ['responsive'],
      zIndex: ['responsive'],
    },
    theme: {
      fontFamily: {
        body: ['Roboto', 'sans-serif'],
      },
      screens: {
        'xs': '425px',
        'sm': '576px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1200px',
        'xxl': '1400px',
      },
      colors: {
        gray: {
            '800': '#292929'
        },
        black: '#171717',
        white: '#fff'
      }
    }
  }